from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, Integer, String, JSON, func
from sqlalchemy.orm import Mapped, mapped_column

from app.db.postgres.session import Base

class DetectionAlert(Base):
    """
    Stores alerts generated by the detection service based on Wazuh events.
    """
    __tablename__ = "detection_alerts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str | None] = mapped_column(String(1000), nullable=True)
    use_case: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    severity: Mapped[str] = mapped_column(String(50), default="medium", nullable=False)
    
    source_ip: Mapped[str | None] = mapped_column(String(120), index=True, nullable=True)
    
    # Storing related info (e.g. user, ports, geoip)
    details: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=func.now(), index=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
