import { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import html2canvas from "html2canvas";

interface ExportPdfButtonProps {
  reportTitle: string;
  filename: string;
  targetId: string; // The ID of the container with charts to capture
  stats: { label: string; value: string | number }[];
  tableData?: {
    head: string[][];
    body: (string | number)[][];
  };
  recommendations?: string[];
  label?: string;
}

export function ExportPdfButton({
  reportTitle,
  filename,
  targetId,
  stats,
  tableData,
  recommendations = [
    "Monitor critical findings for immediate remediation.",
    "Perform a full system sync if data appears stale.",
    "Review active agents status periodically.",
  ],
  label = "Export PDF",
}: ExportPdfButtonProps) {
  const [loading, setLoading] = useState(false);

  const generatePdf = async () => {
    setLoading(true);
    try {
      const doc = jsPDF({
        orientation: "p",
        unit: "mm",
        format: "a4",
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 15;
      const dateStr = new Date().toLocaleString();

      // --- 1. Cover Page ---
      // Logo (Placeholder Circle)
      doc.setFillColor(79, 134, 255);
      doc.circle(pageWidth / 2, 60, 15, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("MW", pageWidth / 2, 62, { align: "center" });

      // Title
      doc.setTextColor(30, 41, 59);
      doc.setFontSize(26);
      doc.text("Middleware-1.0", pageWidth / 2, 100, { align: "center" });
      doc.setFontSize(18);
      doc.setFont("helvetica", "normal");
      doc.text(reportTitle, pageWidth / 2, 115, { align: "center" });

      // Meta
      doc.setFontSize(10);
      doc.setTextColor(100, 116, 139);
      doc.text(`Generated Date: ${dateStr}`, pageWidth / 2, 160, { align: "center" });
      doc.text(`Generated By: System Administrator`, pageWidth / 2, 167, { align: "center" });
      doc.text(`Status: Official Report`, pageWidth / 2, 174, { align: "center" });

      // Footer Cover
      doc.setFontSize(8);
      doc.text("Middleware-1.0 Confidential", pageWidth / 2, pageHeight - 15, { align: "center" });

      // --- 2. Executive Summary ---
      doc.addPage();
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(79, 134, 255);
      doc.text("1. Executive Summary", margin, 25);
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(51, 65, 85);
      const summaryText = "This report provides an automated overview of the current system state, security findings, and performance metrics as captured from the Middleware-1.0 dashboard. The data highlights key performance indicators (KPIs) and recent activities that require administrative attention.";
      const splitSummary = doc.splitTextToSize(summaryText, pageWidth - margin * 2);
      doc.text(splitSummary, margin, 35);

      // Statistics Grid
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("2. Key Statistics", margin, 60);

      let currentY = 70;
      stats.forEach((stat, i) => {
        const xPos = i % 2 === 0 ? margin : pageWidth / 2 + 5;
        doc.setFillColor(248, 250, 252);
        doc.rect(xPos, currentY, (pageWidth - margin * 2) / 2 - 5, 20, "F");
        doc.setFontSize(9);
        doc.setTextColor(100, 116, 139);
        doc.text(stat.label, xPos + 5, currentY + 7);
        doc.setFontSize(12);
        doc.setTextColor(30, 41, 59);
        doc.text(String(stat.value), xPos + 5, currentY + 15);
        if (i % 2 !== 0) currentY += 25;
      });

      // --- 3. Charts Summary ---
      const chartElement = document.getElementById(targetId);
      if (chartElement) {
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(79, 134, 255);
        doc.text("3. Visual Analysis", margin, currentY + 15);

        const canvas = await html2canvas(chartElement, {
          backgroundColor: "#070d1a",
          scale: 2,
        });
        const imgData = canvas.toDataURL("image/png");
        const imgWidth = pageWidth - margin * 2;
        const imgHeight = (canvas.height * imgWidth) / canvas.width;
        
        // Check if chart fits or add new page
        if (currentY + 25 + imgHeight > pageHeight - 30) {
          doc.addPage();
          currentY = 20;
        } else {
          currentY += 25;
        }
        
        doc.addImage(imgData, "PNG", margin, currentY, imgWidth, imgHeight);
        currentY += imgHeight + 15;
      } else {
        currentY += 15;
      }

      // --- 4. Tables ---
      if (tableData) {
        if (currentY > pageHeight - 60) {
          doc.addPage();
          currentY = 20;
        }
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(79, 134, 255);
        doc.text("4. Detailed Records", margin, currentY);

        autoTable(doc, {
          startY: currentY + 5,
          head: tableData.head,
          body: tableData.body,
          theme: "striped",
          headStyles: { fillColor: [79, 134, 255] },
          margin: { left: margin, right: margin },
        });
        
        currentY = (doc as any).lastAutoTable.finalY + 15;
      }

      // --- 5. Recommendations ---
      if (currentY > pageHeight - 50) {
        doc.addPage();
        currentY = 25;
      }
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(79, 134, 255);
      doc.text("5. Recommendations", margin, currentY);

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(51, 65, 85);
      recommendations.forEach((rec, i) => {
        doc.text(`• ${rec}`, margin + 5, currentY + 10 + i * 7);
      });

      // --- Footer for all content pages ---
      const pageCount = (doc as any).internal.getNumberOfPages();
      for (let i = 2; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: "right" });
        doc.text("Middleware-1.0 Enterprise Report", margin, pageHeight - 10);
      }

      doc.save(`${filename}-${new Date().toISOString().split("T")[0]}.pdf`);
    } catch (error) {
      console.error("PDF Generation Error:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      className={`button ${loading ? "button--ghost" : "button--secondary"}`}
      onClick={generatePdf}
      disabled={loading}
    >
      {loading ? (
        <>
          <div className="spinner" />
          Processing...
        </>
      ) : (
        <>
          <svg width="15" height="15" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
          </svg>
          {label}
        </>
      )}
      <style>{`
        .spinner {
          width: 14px;
          height: 14px;
          border: 2px solid rgba(255,255,255,0.3);
          border-top-color: #fff;
          border-radius: 50%;
          animation: spin 0.8s linear infinite;
        }
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
      `}</style>
    </button>
  );
}
